AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Name:
    Type: String
    Description: Name of the app
  
Resources:
  DomainS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: cloud-resume-challenge-oliver.com
      WebsiteConfiguration:
        ErrorDocument: 404.html
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: FALSE
  DomainS3HostingBucketPolicy:
   Type: AWS::S3::BucketPolicy
   Properties:
      Bucket: !Ref DomainS3Bucket
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${DomainS3Bucket}/*"
  DomainRecordSet:
   Type: AWS::Route53::RecordSet
   Properties:
    HostedZoneId: Z05331763E8JY263AVOS6
    Name: !Ref DomainS3Bucket
    Type: A
    AliasTarget:
     DNSName: !Sub "s3-website-${AWS::Region}.amazonaws.com"
     HostedZoneId: Z3BJ6K6RIION7M
  
  SubDomainS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "www.${DomainS3Bucket}"
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref DomainS3Bucket
          Protocol: http

  SubDomainRecordSet:
   Type: AWS::Route53::RecordSet
   Properties:
    HostedZoneId: Z05331763E8JY263AVOS6
    Name: !Ref SubDomainS3Bucket
    Type: A
    AliasTarget:
     DNSName: !Sub "s3-website-${AWS::Region}.amazonaws.com"
     HostedZoneId: Z3BJ6K6RIION7M

  CloudDistribution:
   Type: AWS::CloudFront::Distribution
   Properties:
    DistributionConfig:
     Aliases:
      - !Ref DomainS3Bucket
      - !Ref SubDomainS3Bucket
     Origins:
      DomainName: !Ref DomainS3Bucket
      Id: CustomIdForNow
      CustomOriginConfig:
        OriginProtocolPolicy: match-viewer
     Enabled: 'true'
     DefaultRootObject: index.html
     PriceClass: PriceClass_All
     Logging:
       Bucket: !Ref DomainS3Bucket
     ViewerCertificate:
       CloudFrontDefaultCertificate: 'true'

    


 
