AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Name:
    Type: String
    Description: Name of the app
  
Resources:
  DomainS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: cloud-resume-challenge-oliver.com
      WebsiteConfiguration:
        ErrorDocument: 404.html
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: FALSE
  DomainS3HostingBucketPolicy:
   Type: AWS::S3::BucketPolicy
   Properties:
      Bucket: !Ref DomainS3Bucket
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${DomainS3Bucket}/*"
  DomainRecordSet:
   Type: AWS::Route53::RecordSet
   Properties:
    HostedZoneId: Z05331763E8JY263AVOS6
    Name: cloud-resume-challenge-oliver.com
    Type: A
    Region: !Ref AWS::Region
    TTL: 300
    AliasTarget:
     DNSName: !Sub "s3-website-${AWS::Region}.amazonaws.com"
     HostedZoneId: Z05331763E8JY263AVOS6

  SubDomainS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "www.${DomainS3Bucket}"
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref DomainS3Bucket
          Protocol: http
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: FALSE
  SubDomainS3HostingBucketPolicy:
   Type: AWS::S3::BucketPolicy
   Properties:
      Bucket: !Ref SubDomainS3Bucket
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${SubDomainS3Bucket}/*"

 
