AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Name:
    Type: String
    Description: Name of the app
  
Resources:
  DomainS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: cloud-resume-challenge-oliver.com
      WebsiteConfiguration:
        ErrorDocument: 404.html
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: FALSE
  DomainS3HostingBucketPolicy:
   Type: AWS::S3::BucketPolicy
   Properties:
      Bucket: cloud-resume-challenge-oliver.com
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${DomainS3Bucket}/*"
  SubDomainS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: www.cloud-resume-challenge-oliver.com
      WebsiteConfiguration:
        ErrorDocument: 404.html
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: FALSE
  SubDomainS3HostingBucketPolicy:
   Type: AWS::S3::BucketPolicy
   Properties:
      Bucket: www.cloud-resume-challenge-oliver.com
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${SubDomainS3Bucket}/*"
