AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Name:
    Type: String
    Description: Name of the app
  
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: cloud-resume-challenge-oliver
      WebsiteConfiguration:
        ErrorDocument: 404.html
        IndexDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: FALSE
          BlockPublicPolicy: FALSE
          IgnorePublicAcls: FALSE
          RestrictPublicBuckets: FALSE
  S3HostingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: cloud-resume-challenge-oliver
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
