name: AWS Lambda & API gateway deployment demonstration
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: 
    - name: Install SAM CLI
      with:
        run: wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
        run: unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
        run: sudo ./sam-installation/install
        run: sam --version